apiVersion: 1

datasources:
  # Loki for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60s
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "request_id=([a-f0-9-]+)"
          name: "request_id"
          url: "/explore?orgId=1&left=[\"now-1h\",\"now\",\"Prometheus\",{\"expr\":\"http_requests_total{request_id=\\\"$${__value.raw}\\\"}\"}]"
    uid: loki

  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    uid: prometheus